// <auto-generated />
using System;
using BodaInvitacionApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodaInvitacionApp.Migrations
{
    [DbContext(typeof(InvitacionContext))]
    partial class InvitacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BodaInvitacionApp.Models.Confirmacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfirmoAsistencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfirmoNoPases")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnvioInvitacion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkWhatsApp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NomeroDeMesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroDePersonas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasesDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Confirmacion");
                });
#pragma warning restore 612, 618
        }
    }
}
